rexray:
  logLevel: info
libstorage:
  service: s3fs
  integration:
    volume:
      operations:
        create:
          default:
            size: 100
        mount:
          rootPath: /
s3fs:
  accessKey: S3FS_ACCESSKEY
  secretKey: S3FS_SECRETKEY
  endpoint: S3FS_ENTRY
  options:
    - use_path_request_style
    - allow_other
    - nonempty