rexray:
  logLevel: info
libstorage:
  service: s3fs
  integration:
    volume:
      operations:
        mount:
          rootPath: /
s3fs:
  endpoint: S3FS_ENTRY
  accessKey: S3FS_ACCESSKEY
  secretKey: S3FS_SECRETKEY
  options:
    - url=S3FS_ENTRY
    - use_path_request_style
    - allow_other
    - nonempty